### PR TITLE
Comitting first iteration, the page size should be fixed hopefully

### PR DESCRIPTION
**Pull request by aldamrau**
(●__●)

### CODE REVIEW

**Review by BrandonBSaysWhat — DISMISSED** [review]
Fix Next Button plesase

**Review by lwhitelaw — APPROVED** [review]
nothing obviously wrong with the button

**Comment by BrandonBSaysWhat** [comment]
The Next button is still not in its appropriate location when zoomed in and out. This may not be a big enough of a deal to care about, just fyi.

**Review by lwhitelaw — APPROVED** [review]

**Review by HannahMTaylor — APPROVED** [review]
approved

**Pull request merged**
